<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>PunchClock</AssemblyName>
    <RootNamespace>PunchClock.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PunchClock.Core\PunchClock.Core.csproj" />
    <ProjectReference Include="..\PunchClock.Data\PunchClock.Data.csproj" />
  </ItemGroup>

</Project>
